version: '3.8'

services:
  smart-cctv:
    build: .
    container_name: smart-cctv-system
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./models:/app/models
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/New_York
      - CAMERA_1_PASSWORD=${CAMERA_1_PASSWORD:-changeme}
      - CAMERA_2_PASSWORD=${CAMERA_2_PASSWORD:-changeme}
      - CAMERA_3_PASSWORD=${CAMERA_3_PASSWORD:-changeme}
      - CAMERA_4_PASSWORD=${CAMERA_4_PASSWORD:-changeme}
      - PYTHONPATH=/app/src
      - YOLO_CONFIG_DIR=/app/models
    # devices:
    #   - /dev/snd:/dev/snd  # Audio devices for sound output
    # For GPU support (uncomment if using NVIDIA GPU)
    # runtime: nvidia
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all
    #   - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Model downloader service (run once to pre-download models)
  model-downloader:
    build: .
    container_name: smart-cctv-downloader
    profiles: ["tools"]  # Only run when explicitly called
    volumes:
      - ./models:/app/models
    environment:
      - PYTHONPATH=/app/src
    command: python scripts/download_models.py --model yolov8n.pt --models-dir /app/models

  # Optional: Web dashboard service
  # smart-cctv-web:
  #   build: .
  #   container_name: smart-cctv-web
  #   command: python src/web/app.py
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - ./config:/app/config:ro
  #     - ./data:/app/data:ro
  #   depends_on:
  #     - smart-cctv
