# System Configuration
system:
  name: "Home CCTV System"
  log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  data_dir: "./data"
  models_dir: "./models"

# Camera Configurations
cameras:
  - id: "camera_1"
    name: "Front Door"
    url: "rtsp://username:password@<ipAdress>/stream1"
    location: "front_entrance"
    enabled: true
    fps: 25
    calibration_file: "config/calibration/camera_1.json"
    reference_points:
      - name: "front_door"
        position: [960, 1000]  # pixel coordinates (x, y)
        real_distance: 3.0      # meters from camera
    zones:
      - name: "entrance_zone"
        polygon: [[100, 500], [1820, 500], [1820, 1000], [100, 1000]]
        type: "critical"

  - id: "camera_2"
    name: "Backyard"
    url: "rtsp://admin:password@<ipAdress>/stream1"
    location: "back_yard"
    enabled: true
    fps: 25
    calibration_file: "config/calibration/camera_2.json"
    reference_points:
      - name: "back_door"
        position: [960, 900]
        real_distance: 4.0

  - id: "camera_3"
    name: "Side Entrance"
    url: "rtsp://admin:password@<ipAdress>/stream1"
    location: "side_entrance"
    enabled: true
    fps: 25
    calibration_file: "config/calibration/camera_3.json"

  - id: "camera_4"
    name: "Garage"
    url: "rtsp://admin:password@<ipAdress>/stream1"
    location: "garage"
    enabled: true
    fps: 25
    calibration_file: "config/calibration/camera_4.json"
    reference_points:
      - name: "car"
        position: [1200, 800]
        real_distance: 5.0

# Processing Configuration
processing:
  detection:
    model: "yolov8n"  # yolov8n, yolov8s, yolov8m, yolov8l
    device: "cpu"  # cpu, cuda:0, mps (Mac)
    confidence_threshold: 0.5
    nms_threshold: 0.4
    input_size: [640, 640]
    classes_filter: ["person", "car", "truck", "motorcycle", "dog", "cat", "bird"]
    batch_size: 1
  
  tracking:
    max_age: 30          # frames to keep lost tracks
    min_hits: 3          # minimum detections to confirm track
    iou_threshold: 0.3   # IoU threshold for matching
  
  distance:
    method: "calibration"  # calibration or midas
    unit: "meters"
    max_distance: 50.0

# Performance Settings
performance:
  fps_limit: 15           # Max FPS to process (0 = no limit)
  frame_skip: 0           # Skip every N frames (0 = no skip)
  thread_pool_size: 4     # Number of processing threads

# Storage Settings
storage:
  events_retention_days: 30
  snapshots_retention_days: 7
  log_rotation_mb: 100
  database_path: "./data/events.db"
  snapshots_dir: "./data/snapshots"

# Alert Rules
alert_rules:
  - name: "Night Intruder Detection"
    enabled: true
    priority: "critical"
    conditions:
      camera_ids: ["camera_1", "camera_2"]
      time_range: ["22:00", "06:00"]
      object_class: "person"
      distance_to_reference:
        reference: "front_door"
        operator: "less_than"
        value: 5.0
    actions:
      - type: "audio_alert"
        message: "Warning! Person detected near entrance at night."
        speaker: "all"
      - type: "snapshot"
      - type: "log"
        severity: "critical"
    cooldown: 60

  - name: "Vehicle Proximity Alert"
    enabled: true
    priority: "high"
    conditions:
      camera_ids: ["camera_4"]
      object_class: "person"
      distance_to_reference:
        reference: "car"
        operator: "less_than"
        value: 3.0
    actions:
      - type: "audio_alert"
        message: "Alert: Person detected near your vehicle."
        speaker: "living_room"
      - type: "snapshot"
    cooldown: 30

  - name: "Daytime Visitor"
    enabled: true
    priority: "low"
    conditions:
      camera_ids: ["camera_1"]
      time_range: ["08:00", "20:00"]
      object_class: "person"
      distance_to_reference:
        reference: "front_door"
        operator: "less_than"
        value: 2.0
    actions:
      - type: "audio_alert"
        message: "Visitor at front door."
        speaker: "living_room"
      - type: "snapshot"
    cooldown: 120

# Speaker Configuration
speakers:
  - name: "living_room"
    type: "wired"  # wired or bluetooth
    device_id: 0   # For wired, system audio device ID
    enabled: true
  
  - name: "bedroom"
    type: "bluetooth"
    mac_address: "AA:BB:CC:DD:EE:FF"  # Bluetooth speaker MAC
    enabled: false
  
  - name: "all"
    type: "group"
    speakers: ["living_room", "bedroom"]

# Text-to-Speech Configuration
tts:
  engine: "gtts"  # pyttsx3 or gtts
  language: "en" # Language code for gtts
  tld: "com"  # Top-level domain for gtts
  slow: false  # Slow speech for gtts
  cache_enabled: true
  cache_dir: "./data/tts_cache"

# Web Interface (Optional)
ui:
  enabled: false
  host: "0.0.0.0"
  port: 5000
  auth_enabled: true
  username: "admin"
  password: "changeme"  # Please change this!
  ssl_enabled: false

# Monitoring (Optional)
monitoring:
  prometheus_enabled: false
  prometheus_port: 8000
  health_check_interval: 60
